### PR TITLE
Introducing modelValue and valueTransformer to address differences in field value vs display

### PR DESCRIPTION
**Pull request by zats**
Added two properties on `EZFormField`:  `modelValue` and `valueTransformer`
Used to definitive between "model" level value and "presented" (field) value. 
`valueTransformer` is a concept taken from Mantle: it converts `model` value into a `field` value and vice versa 
API is backward compatible but allows a cleaner separation when you want to display values differently comparing to what you store in your model. An example:

```objectivec
numberFormatter.numberStyle = NSNumberFormatterSpellOutStyle;
EZFormTextField *field = [form formFieldForKey:@"count"];
field.valueTransformer = [EZReversableValueTransformer reversableValueTransformerWithForwardBlock:^id(NSString *value) {
    return [numberFormatter numberFromString:value];
} reverseBlock:^id(NSNumber *number) {
    return [numberFormatter stringFromNumber:number];
}];
```

Plus slight syntax modernisation.

### CODE REVIEW

**Comment by zats** [comment]
@chrismiles is this thing on?

**Comment by chrismiles** [comment]
Thanks, some nice cleanup & modernisation too.

Any chance of updating the demo app with examples of the transformers?

**Comment by zats** [comment]
Hey Chris, thanks for merging. 
Valid point regarding the demo, expect another pull request soon:)

**Comment by bok-** [comment]
Hi guys,

Just a quick note that I'm cleaning up some of the changes introduced in this pull request prior to the back porting of the changes I made for [Pocket Console](http://pocketconsoleapp.com/), such as child form support and form field groups (to support dynamic form lengths).

In order to standardise the changes here, code compiled against this pull request will **break** as the following changes will be made:

* EZReversableValueTransformer -> EZFormReversibleValueTransformer
* EZTranformationBlock -> EZFormValueTransformationBlock
* EZFormValueTransformer will be added to allow for forward-only transformations.
* Form fields will support any NSValueTransformer instance or subclass, not only EZFormReversibleValueTransformers.
* The roles of the forwardBlock and reverseBlock will be switched.

In Mantle, and as described in the pull request, the forward transformation is used when _importing_ values to the model, and the reverse transformation for *exporting* from the Model. I believe they should be used in the same way for form fields, especially in light of forward-only transformations and child forms later on.

-Rob

**Comment by zats** [comment]
Hey Rob, that's great and sound like a needed improvement!
Probably best to bump the cocoapods version since changes are not backward compatible.

**Comment by bok-** [comment]
I was going to do so then realised @chrismiles didn't actually create a release for 1.1.5 yet (nor push it to the cocoapods trunk), so the only affected people will be those pointing directly at master on this repo.

**Comment by zats** [comment]
Khmm, that's me😀 could you please post here once you push. Appreciate it!

**Comment by bok-** [comment]
The update was pushed to master a few minutes ago. We'll update again when the live CocoaPods version has been bumped.

**Comment by zats** [comment]
Thanks!

**Pull request merged**
